# Generated by Django 5.2.1 on 2025-06-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=100)),
                ("departamento", models.CharField(max_length=100)),
                ("materiais", models.TextField(blank=True)),
                (
                    "pre_requisitos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="disciplinas_requeridas",
                        to="disciplinas.disciplina",
                    ),
                ),
                (
                    "professores",
                    models.ManyToManyField(
                        limit_choices_to={"role": "teacher"},
                        related_name="disciplinas",
                        to="account.profile",
                    ),
                ),
            ],
        ),
    ]
