# Generated by Django 5.2.1 on 2025-06-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='graduacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Obrigatória', 'Obrigatória'), ('Eletiva', 'Eletiva')], max_length=20, null=True),
        ),
    ]
