# Generated by Django 5.2.1 on 2025-06-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_disciplina_graduacao_disciplina_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='breve_descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
