# Generated by Django 5.2.1 on 2025-06-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0003_disciplina_breve_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='creditos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
