# Generated by Django 5.2.1 on 2025-06-16 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("disciplinas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvaliacaoDisciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avaliacao", models.TextField()),
                (
                    "aluno",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_disciplinas",
                        to="account.profile",
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="disciplinas.disciplina",
                    ),
                ),
            ],
        ),
    ]
